# image will be published to ghcr.io/<user>/<name>
name: silverblue-nobara-kernel
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - zsh
      - android-tools
      - tlp
      - tlp-rdw
      - distrobox
      - podman
      - gnome-shell-extension-gsconnect
      - tailscale
      - gnome-boxes
    remove:
      - firefox
      - firefox-langpacks
      # - power-profiles-daemon
      - gnome-system-monitor
      - gnome-shell-extension-background-logo
      # - kernel 
      # - kernel-core 
      # - kernel-modules 
      # - kernel-modules-core 
      # - kernel-modules-extra
      # - gnome-extensions

    # Use Nobara Kernel
    replace:
    - from-repo: https://copr.fedorainfracloud.org/coprs/gloriouseggroll/nobara-41/repo/fedora-41/gloriouseggroll-nobara-41-fedora-41.repo
      packages:
      - kernel 
      - kernel-core 
      - kernel-modules 
      - kernel-modules-core 
      - kernel-modules-extra

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - com.vscodium.codium
        - io.github.zen_browser.zen
        - io.missioncenter.MissionCenter
        - com.mattjakeman.ExtensionManager
        - org.mozilla.Thunderbird
        - io.github.dvlv.boxbuddyrs
      remove:
      # - org.gnome.eo

  - type: gnome-extensions
    install:
      - 307 #DASH TO DOCK
      - 517 #CAFFEINE
      - 3780 #DDTERM
      - 615 #AppIndicator and KStatusNotifierItem Support
      - 6139 #Tailscale QS
    uninstall:
      - 6 #APPSMENU
      #- 889 #BACKGROUND LOGO

  - type: systemd
    system:
      enabled:
        - tlp.service
        - podman.service
        - tailscaled.service
        
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
