# image will be published to ghcr.io/<user>/<name>
name: silverblue-nobara-kernel
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos/repo/fedora-%OS_VERSION%/bieszczaders-kernel-cachyos-fedora-%OS_VERSION%.repo
    install:
      - zsh
      - android-tools
      - tlp-rdw
      - distrobox
      - podman
      - gnome-shell-extension-gsconnect
      - tailscale
      - gnome-boxes
      - https://repo.linrunner.de/fedora/tlp/repos/releases/tlp-release.fc%OS_VERSION%.noarch.rpm
      - kernel-cachyos
    remove:
      - firefox
      - firefox-langpacks
      #- power-profiles-daemon #changed from Fedora 41 on to tuned tuned-ppd
      - tuned 
      - tuned-ppd
      - gnome-system-monitor
      - gnome-shell-extension-background-logo
      - kernel 
      - kernel-core 
      - kernel-modules 
      - kernel-modules-core 
      - kernel-modules-extra
      # - gnome-extensions

    replace:
      - from-repo: https://copr.fedorainfracloud.org/coprs/trixieua/mutter-patched/repo/fedora-%OS_VERSION%/trixieua-mutter-patched-fedora-%OS_VERSION%.repo
      packages:
        - mutter
        - mutter-common
        - gdm

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - com.vscodium.codium
        - io.github.zen_browser.zen
        - io.missioncenter.MissionCenter
        - com.mattjakeman.ExtensionManager
        - org.mozilla.Thunderbird
        - io.github.dvlv.boxbuddyrs
        - com.usebottles.bottles
        - io.github.bkbilly.lnxlink
        - io.github.martchus.syncthingtray
        - io.github.ungoogled_software.ungoogled_chromium
        - io.missioncenter.MissionCenter
        - org.gimp.GIMP
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.FileRoller
        - org.gnome.Loupe
        - org.gnome.font-viewer
        - org.inkscape.Inkscape
        - org.gnome.gedit
        - org.signal.Signal
        - org.videolan.VLC
      remove:
      # - org.gnome.eo

  - type: gnome-extensions
    install:
      - 307 #DASH TO DOCK
      - 517 #CAFFEINE
      #- 3780 #DDTERM
      - 615 #AppIndicator and KStatusNotifierItem Support
      - 6139 #Tailscale QS
    uninstall:
      - 6 #APPSMENU
      #- 889 #BACKGROUND LOGO

  - type: systemd
    system:
      enabled:
        - tlp.service
        - podman.service
        - tailscaled.service
      mask:
        - systemd-rfkill.service 
        - systemd-rfkill.socket
        
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
