# image will be published to ghcr.io/<user>/<name>
name: silverblue-nobara-kernel
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      # - micro
      # - starship
      - zsh
      - android-tools
      - tlp
      - tlp-rdw
    remove:
      - firefox
      - firefox-langpacks
      - power-profiles-daemon
      
    replace:
    - from-repo: https://copr.fedorainfracloud.org/coprs/gloriouseggroll/nobara-40/repo/fedora-%OS_VERSIONS%/gloriouseggroll-nobara-40-fedora-%OS_VERSION%.repo 
      packages:
      - kernel 
      - kernel-core 
      - kernel-modules 
      - kernel-modules-core 
      - kernel-modules-extra

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - com.vscodium.codium
        - io.github.zen_browser.zen
      remove:
      # - org.gnome.eo

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
